apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-grafana-dashboards
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    chart: cloudnative-pg
    repoURL: https://cloudnative-pg.github.io/charts
    targetRevision: 0.19.0 # Aktuelle CNPG Version
    helm:
      values: |
        grafana:
          dashboards:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system # Namespace des CNPG Operators
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
