apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - qa-appset.yaml
  # Uncomment these when you're ready for staging/production
  # - staging-appset.yaml
  # - production.yaml
