apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-production-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/Tim275/kubecraft.git
        revision: HEAD
        directories:
          - path: argocd/apps/*/envs/production
          - path: argocd/infrastructure/cnpg/envs/production
  template:
    metadata:
      name: "{{ if eq (index .path.segments 1) 'infrastructure' }}cnpg-production{{ else }}{{ index .path.segments 2 }}-production{{ end }}"
    spec:
      project: default
      source:
        repoURL: https://github.com/Tim275/kubecraft.git
        targetRevision: HEAD
        path: "{{ .path.path }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ if eq (index .path.segments 1) 'infrastructure' }}cnpg-system{{ else }}{{ index .path.segments 2 }}-production{{ end }}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
