apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-qa-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/Tim275/kubecraft.git
        revision: HEAD
        directories:
          - path: argocd/apps/*/envs/qa
          - path: argocd/infrastructure/*/envs/qa
  template:
    metadata:
      name: '{{ if eq (index .path.segments 1) "infrastructure" }}cnpg-qa{{ else }}{{ index .path.segments 2 }}-qa{{ end }}'
      annotations:
        # Set infrastructure to sync before applications
        argocd.argoproj.io/sync-wave: '{{ if eq (index .path.segments 1) "infrastructure" }}-1{{ else }}0{{ end }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Tim275/kubecraft.git
        targetRevision: HEAD
        path: "{{ .path.path }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ if eq (index .path.segments 1) "infrastructure" }}cnpg-system{{ else }}{{ index .path.segments 2 }}-qa{{ end }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true # Add ServerSideApply to handle large CRDs
