apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: qa-apps-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/Tim275/kubecraft.git
        revision: HEAD
        directories:
          - path: argocd/apps/*/envs/qa
  template:
    metadata:
      name: "{{index .path.segments 2}}-qa"
      annotations:
        argocd.argoproj.io/sync-wave: "5"
    spec:
      project: default
      source:
        repoURL: https://github.com/Tim275/kubecraft.git
        targetRevision: HEAD
        path: "{{.path.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{index .path.segments 2}}-qa"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
