apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: qa-cnpg-appset
  namespace: argocd
spec:
  goTemplate: true # Add this to enable template processing
  goTemplateOptions: ["missingkey=error"] # Add this for error handling
  generators:
    - git:
        repoURL: https://github.com/Tim275/kubecraft.git
        revision: HEAD
        directories:
          - path: argocd/infrastructure/cnpg/envs/qa
  template:
    metadata:
      name: "cnpg-qa"
      annotations:
        argocd.argoproj.io/sync-wave: "-5"
    spec:
      project: default
      source:
        repoURL: https://github.com/Tim275/kubecraft.git
        targetRevision: HEAD
        path: "{{ .path.path }}" # Add spaces for proper Go template syntax
      destination:
        server: https://kubernetes.default.svc
        namespace: "cnpg-system"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
