apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-staging-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/Tim275/kubecraft.git
        revision: HEAD
        directories:
          - path: argocd/apps/*/envs/staging
          - path: argocd/infrastructure/*/envs/staging
  template:
    metadata:
      name: '{{ if eq (index .path.segments 1) "infrastructure" }}cnpg-staging{{ else }}{{ index .path.segments 2 }}-staging{{ end }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Tim275/kubecraft.git
        targetRevision: HEAD
        path: "{{ .path.path }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ if eq (index .path.segments 1) "infrastructure" }}cnpg-system{{ else }}{{ index .path.segments 2 }}-staging{{ end }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
