apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-argocd-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Tim275/kubecraft.git
    targetRevision: HEAD
    path: argocd/appsets
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
